
- project:
    queue: vitrage
    templates:
      - check-requirements
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py38
        - openstack-tox-py310

    gate:
      jobs:
        - openstack-tox-py38
        - openstack-tox-py310
